#!/usr/bin/env python3
"""
Convert PNG sprite images to ESP32 RGB565 C header files.

Usage:
  python png_to_sprite.py idle.png walk.png sleep.png --size 32 --out pig_sprites.h

Each PNG is one animation. If the image is wider than --size, it's treated
as a horizontal sprite sheet (multiple frames side by side).
Single-frame PNGs (e.g. a portrait) produce a 1-frame animation.

Output: C header with RGB565 arrays (byte-swapped for GC9A01 SPI) and
sprite_animation_t structs ready to pass to sprite_engine_load().
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow required: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def rgb565_be(r, g, b):
    c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return ((c >> 8) & 0xFF) | ((c & 0xFF) << 8)


def convert_image(img, sprite_size):
    img = img.convert("RGBA")

    if img.height != sprite_size:
        ratio = sprite_size / img.height
        img = img.resize((int(img.width * ratio), sprite_size), Image.NEAREST)

    frame_count = max(1, img.width // sprite_size)
    frames = []

    for f in range(frame_count):
        frame = []
        for y in range(sprite_size):
            for x in range(sprite_size):
                px_x = f * sprite_size + x
                if px_x < img.width:
                    r, g, b, a = img.getpixel((px_x, y))
                    frame.append(0x0000 if a < 128 else rgb565_be(r, g, b))
                else:
                    frame.append(0x0000)
        frames.append(frame)

    return frames


def write_header(animations, sprite_size, output_path):
    with open(output_path, "w") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write('#include "sprite_engine.h"\n\n')
        f.write(f"// Generated by png_to_sprite.py\n")
        f.write(f"// Sprite size: {sprite_size}x{sprite_size}, RGB565 byte-swapped for GC9A01\n\n")

        for anim_name, frames in animations:
            total_px = len(frames) * sprite_size * sprite_size
            f.write(f"static const uint16_t {anim_name}_frames[{total_px}] = {{\n")
            for fi, frame in enumerate(frames):
                f.write(f"    // Frame {fi}\n")
                for y in range(sprite_size):
                    f.write("    ")
                    for x in range(sprite_size):
                        f.write(f"0x{frame[y * sprite_size + x]:04X},")
                    f.write("\n")
            f.write("};\n\n")

        f.write("static const sprite_animation_t pig_animations[] = {\n")
        for anim_name, frames in animations:
            fc = len(frames)
            f.write(
                f'    {{ .frames = {anim_name}_frames, .frame_count = {fc},'
                f' .frame_delay_ms = 200, .name = "{anim_name}" }},\n'
            )
        f.write("};\n\n")
        f.write(f"#define PIG_ANIMATION_COUNT {len(animations)}\n")

    print(f"Done: {output_path} ({len(animations)} animations)")


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG sprites to ESP32 RGB565 C headers"
    )
    parser.add_argument(
        "images", nargs="+",
        help="PNG files (filename becomes animation name, e.g. idle.png -> idle)"
    )
    parser.add_argument("--size", type=int, default=32, help="Sprite size (default: 32)")
    parser.add_argument("--out", default="pig_sprites.h", help="Output header file")
    args = parser.parse_args()

    animations = []
    for img_path in args.images:
        name = Path(img_path).stem
        img = Image.open(img_path)
        frames = convert_image(img, args.size)
        animations.append((name, frames))
        print(f"  {name}: {len(frames)} frame(s) from {img_path}")

    write_header(animations, args.size, args.out)


if __name__ == "__main__":
    main()
